spring:
  security:
    user:
      name: xxx
      password: xxx
  data:
    redis:
      port: 6379
      host: xxx
      password: xxx
  # 数据源配置
  datasource:
    druid:
      url: xxx
      username: xxx
      password: xxx


rsa:
  private-key: xxx

#jwt
jwt:
  secret: k09BQnaF
  # 必须使用最少88位的Base64对该令牌进行编码
  base64-secret: xxx
  # 令牌过期时间 此处单位/毫秒 ，默认7天，可在此网站生成 https://www.convertworld.com/zh-hans/time/milliseconds.html
  token-validity-in-seconds: 604800000